name: Android

on:
  workflow_dispatch:
  release:
    types: [published]
    branches: [ master ]

jobs:

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: |
          chmod +x build.android.sh
          docker run --rm -i -w /app -v $(pwd):/app -e ANDROID_HOME=/usr/local/android_sdk -e GOPROXY=direct fyneio/fyne-cross:android-latest /app/build.android.sh
      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            android_client.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}